강의 참고자료

<Andrew Ng's ML class>

https://class.coursera.org/ml-003/lecture

http://www.holehouse.org/mlclass/ (강의노트)

## 1) ML lec & lab 01

### Tensor Flow의 개념

- data flow graph를 이용해서 numerical computation을 한다.

- data flow graph는?
    Nodes: 그래프 안에서 원(타원)안에 들어있는 부분. 수학적인 연산을 의미
    Edges: 그래프 안에서 원을 연결하면서 흐름을 나타내는 선.  multidimensional data arrays(=tensor) 


In [ ]:
# tensorflow 설치 여부 및 version 확인

In [ ]:
import tensorflow as tf
tf.__version__

In [ ]:
# hello TensorFlow!

In [ ]:
hello = tf.constant("Hello TensorFlow")
print(hello)

In [ ]:
with tf.Session() as sess:
    _hello = sess.run(hello)
    print(_hello)

In [ ]:
node1 = tf.constant(3.0, tf.float32)
node2 = tf.constant(4.0, tf.float32)
node3 = tf.add(node1, node2)
# node4 = node1 + node2 (tf.add와 동일한 결과)

In [ ]:
print(node1)
print(node2)
print(node3)

In [ ]:
sess = tf.Session()
print('node1 and node2 are respectively', sess.run([node1, node2]))
print('node3 is ', sess.run(node3))

그래프를 build 한다. (tf.constant 등의 define 과정)
그래프를 실행한다. (sess.run)
실행의 결과로 그래프 안의 값들이 업데이트 되거나 리턴된다. 

In [ ]:
# placeholder, variable

In [ ]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
adder_node = a + b

print(sess.run(adder_node, feed_dict={a:3, b:4.5}))
print(sess.run(adder_node, feed_dict={a:[1,3], b:[2, 4]}))

그래프를 만들어 놓고 나면 placeholder를 이용해서 필요한 데이터를 node에 전달하여 하고자 하는 연산의 결과값을 받을 수 있다.

## 2) ML lec & lab 02: Linear Regression

x = [1, 2, 3] 에 상응하는 y=[1, 2, 3] 

이 때 선형회귀방법으로 w를 추정하기

In [ ]:
import tensorflow as tf

#### (1) Define

In [ ]:
# x, y data
x = [1, 2, 3]
y = [1, 2, 3]

W = tf.Variable(tf.random_normal([1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis: y = W*x + b
yhat = W*x + b
cost = tf.reduce_mean(tf.square(yhat - y))

# Optimizer: cost function값의 최소화
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)

#### (2) Run

In [ ]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer()) # variable w, b를 사용하기 위함
    for i in range(2001):
        sess.run(train)
        if i %200==0:
            print('step: {}, cost: {}, w: {}, b: {}'
                  .format(i, sess.run(cost), sess.run(W), sess.run(b)))


#### placeholder를 이용한 데이터 전달 방법

In [ ]:
import tensorflow as tf
X = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

W = tf.Variable(tf.random_normal([1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis: y = W*x + b
yhat = W*X + b
cost = tf.reduce_mean(tf.square(yhat - y))

# Optimizer: cost function값의 최소화
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)

In [ ]:
sess = tf.Session()
sess.run(tf.global_variables_initializer()) # variable w, b를 사용하기 위함
for i in range(2001):
    _cost, _W, _b, _ = sess.run([cost, W, b, train], 
                                feed_dict={X: [1, 2, 3, 4, 5], y:[2.1, 3.1, 4.1, 5.1, 6.1]})
    if i %200==0:
        print('step: {}, cost: {}, W: {}, b: {}'
                .format(i, _cost, _W, _b))

In [ ]:
# Testing(검증): W = 1, b =1.1에 가까우면 잘 된 예측으로 볼 수 있다. 

In [ ]:
print(sess.run(yhat, feed_dict={X: [5]}))
print(sess.run(yhat, feed_dict={X: [6, 7, 8]}))
print(sess.run(yhat, feed_dict={X: [2.5, 3.5, 4.5]}))

## 3) ML lec & lab 03

### Linear Regression의 cost function 최소화

잔차제곱의 평균으로 정의된 cost function cost(W, b)을 그래프로 그려보면 포물선 형태의 곡선이 된다. (b=0으로 가정하여 단순화했을 때)

이 곡선에서 cost(W, b)가 최소가 되는 W, b를 찾는 것

어떻게 cost(W, b)가 최소가 되는 지점을 찾을 것인가? => Gradient Descent algorithm

cost function의 형태가 convex function이면 어느 점에서 시작해도 cost function의 최저점을 찾을 수 있다. 하지만 비용함수가 convex function이 아닐 경우 시작 위치에 따라 비용함수 최저값이 다를게 나타날 수 있음

In [ ]:
import tensorflow as tf
import matplotlib.pyplot as plt

In [ ]:
X = [1, 2, 3]
y = [1, 2, 3]
W = tf.placeholder(tf.float32)
yhat = W*X
cost = tf.reduce_mean(tf.square(yhat - y))

In [ ]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
W_val = []
cost_val =[]
for i in range(-30, 50):
    feed_W = i * 0.1
    curr_cost, curr_W = sess.run([cost, W], feed_dict={W: feed_W})
    W_val.append(curr_W)
    cost_val.append(curr_cost)

plt.plot(W_val, cost_val)
plt.show()

In [ ]:
# W를 변화시켜가며 직접 cost 최저점 찾아보기

import tensorflow as tf

X_data = [1, 2, 3]
y_data = [1, 2, 3]

W = tf.Variable(tf.random_normal([1]), tf.float32, name='weight')
X = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

yhat = X*W
cost = tf.reduce_sum(tf.square(yhat-y)) #직접 찾아보려고 .minimize 사용하지 않음

# 수동으로 cost minimize 하기
learning_rate = 0.1
gradient = tf.reduce_mean((W*y - y)*X)
descent = W - learning_rate * gradient
update = W.assign(descent)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(21):
    sess.run(update, feed_dict={X: X_data, y: y_data})
    print(step, sess.run(cost, feed_dict={X: X_data, y: y_data}), sess.run(W))

In [ ]:
## TF code 연습
import tensorflow as tf
X_data = [1, 2, 3]
y_data = [2, 4, 6]

X = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
W = tf.Variable(tf.random_normal([1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')
yhat = W*X + b

cost = tf.reduce_mean(tf.square(yhat - y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(5000):
        _, _cost, _W, _b = sess.run([train, cost, W, b],
                                   feed_dict={X: X_data, y: y_data})
        if i%100==0:
            print('step: {}, cost: {}, Weight: {}, bias: {}'
                 .format(i, _cost, _W, _b))

## 4-1) ML lec & lab 04

### Multivariable linear regression

- Hypothesis: 
$$
H(x) = Wx + b
$$
$$
H(x_{1}, x_{2}, x_{3}) = w_{1}x_{1} + w_{2}x_{2} + w_{3}x_{3} + b
$$


- Cost function, Gradient descent algorithm 은 동일

In [ ]:
import tensorflow as tf

In [ ]:
x1_data = [73, 93, 89, 96, 73]
x2_data = [80, 88, 91, 98, 66]
x3_data = [75, 93, 90, 100, 70]
y_data = [152, 185, 180, 196, 142]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

yhat = x1*w1 + x2*w2 + x3*w3 + b

cost = tf.reduce_mean(tf.square(yhat - y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-05)
train = optimizer.minimize(cost)

In [ ]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for i in range(2001):
    _, _cost, _yhat = sess.run([train, cost, yhat], 
                        feed_dict={x1: x1_data, 
                                   x2: x2_data,
                                   x3: x3_data, 
                                   y: y_data})
    if i%200==0:
        print('cost: {}, predict: {}'.format(_cost, _yhat))

In [ ]:
# 하지만 이런 방법은 변수나 데이터 갯수가 늘어날 경우 코드가 매우 복잡

In [7]:
import tensorflow as tf
import numpy as np

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

x_data = np.vstack((x1_data, x2_data, x3_data)).T
y_data = np.array(y_data).reshape([-1,1])

In [8]:
X = tf.placeholder(tf.float32, shape=[None, 3])
y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')
yhat = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(yhat - y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-05)
train_op = optimizer.minimize(cost)

In [9]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for i in range(2001):
    _, _cost, _yhat = sess.run([train_op, cost, yhat], 
                              feed_dict={X: x_data,
                                         y: y_data})
    if i%100==0:
        print('step: {}, cost: {}, pred{}'.format(i, _cost, _yhat))

step: 0, cost: 157.6249542236328, pred[[ 154.50639343]
 [ 201.94659424]
 [ 190.58752441]
 [ 209.56750488]
 [ 156.08839417]]
step: 100, cost: 20.109107971191406, pred[[ 144.31492615]
 [ 189.36993408]
 [ 178.36618042]
 [ 196.23428345]
 [ 146.43447876]]
step: 200, cost: 19.108577728271484, pred[[ 144.48399353]
 [ 189.25454712]
 [ 178.41860962]
 [ 196.2674408 ]
 [ 146.28707886]]
step: 300, cost: 18.16060447692871, pred[[ 144.64857483]
 [ 189.14219666]
 [ 178.46965027]
 [ 196.29957581]
 [ 146.14367676]]
step: 400, cost: 17.262346267700195, pred[[ 144.80882263]
 [ 189.03282166]
 [ 178.5193634 ]
 [ 196.33079529]
 [ 146.00416565]]
step: 500, cost: 16.411285400390625, pred[[ 144.96482849]
 [ 188.92634583]
 [ 178.56776428]
 [ 196.36105347]
 [ 145.86845398]]
step: 600, cost: 15.604881286621094, pred[[ 145.116745  ]
 [ 188.82272339]
 [ 178.61494446]
 [ 196.39044189]
 [ 145.73646545]]
step: 700, cost: 14.84077262878418, pred[[ 145.26461792]
 [ 188.72180176]
 [ 178.66085815]
 [ 196.41891479]
 [ 145.

In [12]:
# 새로운 데이터 추가하여 예측
print('My score will be', 
      sess.run(yhat, feed_dict={X: [[100, 96, 92]]}))

My score will be [[ 192.46980286]]


## 4-2) ML lec & lab 04

- Multivariable linear regression
- Data를 csv파일에서 읽어오기

In [1]:
import tensorflow as tf
import numpy as np
import csv

/Users/beomyongnho/.pyenv/versions/3.6.1/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [ ]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
x_data = np.vstack((x1_data, x2_data, x3_data)).T
y_data = [152., 185., 180., 196., 142.]
y_data = np.array(y_data).reshape([-1,1])
dataset = np.hstack((x_data, y_data))

x_dataset = './data/X_dataset.csv'
with open(x_dataset, 'w') as csvfile:
    writer = csv.writer(csvfile)
    for i in range(len(dataset)):
        writer.writerow(dataset[i])
    print('X_dataset is written')

In [2]:
xy = np.loadtxt('./data/X_dataset.csv', delimiter=',', dtype=np.float32)
x_dataset = xy[:, 0:-1]
y_dataset = xy[:, [-1]]

In [6]:
print(x_dataset.shape, x_dataset, len(x_dataset))
print(y_dataset.shape, y_dataset)

(5, 3) [[  73.   80.   75.]
 [  93.   88.   93.]
 [  89.   91.   90.]
 [  96.   98.  100.]
 [  73.   66.   70.]] 5
(5, 1) [[ 152.]
 [ 185.]
 [ 180.]
 [ 196.]
 [ 142.]]


이하 linear regression 방법은 앞서 진행한 것과 동일하므로 생략

## 4-3) Queue Runner

file 용량이 커서 한번에 메모리에 올리지 못할 경우 사용. 다음의 세 단계로 이뤄짐

1) filename_queue

2) reader

3) record_default

In [ ]:
# 예시
filename_queue = tf.train.string_input_producer(
    ['data1.csv', 'data2.csv', ...], 
    shuffle=False, 
    name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(finlename_queue)

record_dafaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)